apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv47
  labels:
    app: jenkins47
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/jenkins
