---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins47
  namespace: jenkins1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins47-role
  namespace: jenkins1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins47
  namespace: jenkins1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins47-role
subjects:
- kind: ServiceAccount
  name: jenkins47
  namespace: jenkins1
