apiVersion: v1
kind: Service
metadata:
  name: jenkins47
  namespace: jenkins1
  labels:
    app: jenkins47
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: slave
      port: 50000
      protocol: TCP
    - name: http
      port: 6443
      protocol: TCP
      targetPort: 8090
  selector:
    app: jenkins47
